from __future__ import annotations

import sys
from pathlib import Path
from typing import List, Literal, Optional

import yaml
from pydantic import BaseModel, ConfigDict, Field


class ReferenceMetadata(BaseModel):
    """
    Reference Metadata Schema for the Grain Trading Vertical.
    
    This model defines the exact field names and enum values for the Knowledge Slot's 
    reference documents (contracts, regulations, standards, etc.). It acts as the 
    single source of truth for the gap detection prompt, Q&A prompts, and the 
    `reference_library` table in Cosolvent.
    """
    
    model_config = ConfigDict(
        use_enum_values=True,
        extra="forbid",
        json_schema_extra={
            "description": "Metadata attached to each document and vector chunk in the Knowledge Slot reference library."
        }
    )

    doc_type: Literal[
        "contract", 
        "standard", 
        "regulation", 
        "guide", 
        "report", 
        "specification", 
        "legislation", 
        "policy", 
        "manual", 
        "article", 
        "other"
    ] = Field(
        description="The type of the reference document."
    )
    
    standard: Optional[Literal[
        "GAFTA", 
        "CGC", 
        "USDA", 
        "FGIS", 
        "IUA", 
        "ICC",
        "ISO"
    ]] = Field(
        default=None,
        description="The standard body or framework this document belongs to."
    )
    
    topic: Literal[
        "goods",
        "quantity",
        "pricing",
        "delivery_terms",
        "brokerage",
        "quality_requirements",
        "shipment",
        "appropriation",
        "payment_terms",
        "duties_and_taxes",
        "discharge",
        "weighing",
        "sampling_and_analysis",
        "insurance",
        "force_majeure",
        "default",
        "insolvency",
        "dispute_resolution",
        "circle_trading",
        "notices"
    ] = Field(
        description="Specific topic or clause theme. Used to semantically tag chunks."
    )
    
    jurisdiction: List[str] = Field(
        default_factory=list,
        description="Countries or regions the document applies to."
    )
    
    product_category: List[str] = Field(
        default_factory=list,
        description="Grain commodities this document covers."
    )


def generate_yaml_schema() -> str:
    """Generates the YAML configuration for the Cosolvent system."""
    schema_dict = ReferenceMetadata.model_json_schema()
    
    output = {
        "schema_version": "1.0",
        "reference_metadata_schema": {
            "fields": {}
        }
    }
    
    fields = output["reference_metadata_schema"]["fields"]
    
    for field_name, field_info in schema_dict.get("properties", {}).items():
        base_type = field_info.get("type", "string")
        
        # Pydantic encodes Optional[Literal] with anyOf containing type 'null'.
        if "anyOf" in field_info:
            for item in field_info["anyOf"]:
                if item.get("type") == "string":
                    if "enum" in item:
                         base_type = "enum"
                         fields[field_name] = {
                             "type": "enum",
                             "allowed_values": item["enum"],
                             "description": field_info.get("description", "")
                         }
                    else:
                         fields[field_name] = {
                             "type": "string",
                             "description": field_info.get("description", "")
                         }
                    break
        elif "enum" in field_info:
             fields[field_name] = {
                 "type": "enum",
                 "allowed_values": field_info["enum"],
                 "description": field_info.get("description", "")
             }
        else:
             fields[field_name] = {
                 "type": base_type,
                 "description": field_info.get("description", "")
             }
             if base_type == "array":
                 items = field_info.get("items", {})
                 fields[field_name]["item_type"] = items.get("type", "string")

    return yaml.dump(output, sort_keys=False, default_flow_style=False)


if __name__ == "__main__":
    yaml_content = generate_yaml_schema()
    
    output_path = Path(__file__).parent / "reference_metadata_schema.yaml"
    with output_path.open("w", encoding="utf-8") as f:
        f.write("# Copyright (c) 2026 Mustafa Uzumeri. All rights reserved.\n")
        f.write("#\n")
        f.write("# This file is auto-generated by reference_metadata_schema.py. DO NOT EDIT MANUALLY.\n")
        f.write("# It defines the tag vocabulary for the Cosolvent `reference_library` table\n")
        f.write("# and is part of the Knowledge Slot vertical configuration.\n\n")
        f.write(yaml_content)
        
    print(f"Generated YAML schema at {output_path}")